pipeline{
    agent any

    environment{
        def myString = "Hello World"
        def myNumber = 10
        def myBoolean = true
    }

    stages{
        stage("demo"){
            steps{
                echo "My String: ${myString}"
                echo "My Number: ${myNumber}"
                echo "My Boolean: ${myBoolean}"
            }
        }
    }
}
    